name: okan_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.10.1

dependencies:
  flutter:
    sdk: flutter
  
  # --- TRADUÇÕES (Causa do erro anterior) ---
  flutter_localizations:
    sdk: flutter
  
  # CORREÇÃO: Atualizado para 0.20.2 para funcionar com o Flutter atual
  intl: ^0.20.2
  # -------------------------------------------

  # Vídeos
  youtube_player_flutter: ^9.0.1
  video_player: ^2.8.1
  chewie: ^1.7.1

  # Ícones
  cupertino_icons: ^1.0.8

  # Firebase
  firebase_core: ^3.15.2
  firebase_auth: ^5.7.0
  cloud_firestore: ^5.6.12
  
  # --- PACOTES QUE ESTAVAM FALTANDO ---
  firebase_storage: ^12.4.0  # Versão compatível com firebase_core ^3
  image_picker: ^1.1.2       # Para pegar foto da galeria
  # ------------------------------------

  google_sign_in: ^6.1.0
  fl_chart: ^0.66.0
  url_launcher: ^6.2.0

  # Gerência de Estado e Injeção
  provider: ^6.1.2
  get_it: ^7.7.0
  
  # Utilitários
  equatable: ^2.0.5
  uuid: ^4.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true